#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           FrontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RearLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RearRight,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		//Check the driving code later
		motor[FrontLeft] = vexRT[Ch4] + vexRT[Ch3];
		motor[FrontRight] = vexRT[Ch4] - vexRT[Ch3];
		motor[RearLeft] = vexRT[Ch4] + vexRT[Ch3];
		motor[RearRight] = vexRT[Ch4] - vexRT[Ch3];
	}
}
