#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           FrontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RearLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RearRight,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){
		if (vexRT[Btn7D]==true){
			motor[FrontRight] = 80;
		}
		else if (vexRT[Btn7U]==true){
			motor[FrontLeft] = 80;
		}
		else if (vexRT[Btn7R]==true){
			motor[RearLeft] = 80;
		}
		else if (vexRT[Btn7L]==true){
			motor[RearRight] = 80;
		}
	}
}
