#pragma config(Motor,  port2,           backMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frightMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           fleftMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           intakeMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           middleMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           lshooter1Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lshooter2Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rshooter1Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rshooter2Motor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){
		if (vexRT[Btn5U]== 1) {
			motor[intakeMotor] = 127;
		}
		else if (vexRT[Btn5D] == 1) {
			motor[intakeMotor] = -127;
		}
		else {
			motor[intakeMotor] = 0;
		}
		//The middle motor
		//Upper is towards the back
		if (vexRT[Btn6U]== 1) {
			motor[middleMotor] = 127;
		}
		else if (vexRT[Btn6D] == 1) {
			motor[middleMotor] = -127;
		}
		else {
			motor[middleMotor] = 0;
		}
	}
}
