#pragma config(Motor,  port2,           backMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frightMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           fleftMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           intakeMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           middleMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           lshooter1Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lshooter2Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rshooter1Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rshooter2Motor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
						motor[lshooter1Motor] = vexRT[Ch1];
						motor[lshooter2Motor] = vexRT[Ch2];
						motor[rshooter1Motor] = vexRT[Ch3];
						motor[rshooter2Motor] = vexRT[Ch4];
	/*else {
						motor[lshooter1Motor] = 0;
						motor[lshooter2Motor] = 0;
						motor[rshooter1Motor] = 0;
						motor[rshooter2Motor] = 0;
	}
	*/
}
}
