#pragma config(Motor,  port2,           backMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frightMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           fleftMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           intakeMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           middleMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           lshooter1Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lshooter2Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rshooter1Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rshooter2Motor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//No Partner Joy Stick

	//Right shooter motor is independant
	while (true){
		if (vexRT[Btn6U]==1){
			motor[rshooterMotor] = 127;
		}
		else if (vexRT[Btn6D]==1){
			motor[rshooterMotor] = -127;
		}
		else {
			motor[rshooterMotor] = 0;
		}
	}

	//Left motor shooter
	while (true){
		if (vexRT[Btn5U]==1){
			motor[lshooterMotor] = 127;
		}
		else if (vexRT[Btn5D]==1){
			motor[lshooterMotor] = -127;
		}
		else {
			motor[lshooterMotor] = 0;
		}
	}

	/*Both motors together
	while (true){
	if (vexRT[Btn5U]==1){
	motor[rshooterMotor] = 127;
	motor[lshooterMotor] = 127;
	}
	else if (vexRT[Btn5D]==1){
	motor[rshooterMotor] = -127;
	motor[lshooterMotor] = -127;
	}
	else {
	motor[rshooterMotor] = 0;
	motor[lshooterMotor] = 0;
	}
	}
	*/

}
