#pragma config(Motor,  port2,           Shootermotor1, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Shootermotor2, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Shootermotor3, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           Shootermotor4, tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	for(;;) {
		/*Motor 1 and 2 are already reversed in port configuration
		motor[Shootermotor1] = floor ((vexRT[Ch2]/127)*80);
		motor[Shootermotor2] = floor ((vexRT[Ch2]/127)*80);
		motor[Shootermotor3] = floor ((vexRT7[Ch2]/127)*80);
		motor[Shootermotor4] = floor ((vexRT[Ch2]/127)*80);*/
		int speed = vexRT[Ch2];
		if (speed >= 80) {
			speed = 80;
		}
		motor[Shootermotor1] = speed;
		motor[Shootermotor2] = speed;
		motor[Shootermotor3] = speed;
		motor[Shootermotor4] = speed;
	}
}
