#pragma config(Sensor, dgtl2,  Sonar,          sensorSONAR_cm)
#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           Shootermotor1, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Shootermotor2, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           FrontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port6,           Shootermotor3, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           RearLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           Shootermotor4, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           RearRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          IntakeMotor,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, in2,    Light,          sensorReflection)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Declare variables
//int lightVal = 0;
int sonarVal = 0;
int axis1 = 0;
int axis2 = 0;
int axis3 = 0;
int axis4 = 0;
int speed = 0;
int i = 0;

task sensors()
{
	while (true) {
		//lightVal = 0;
		sonarVal = 0;
		for (i = 1; i < 100; i++){
			//Find light sensor and ultrasonic sensor values
			sonarVal = sonarVal + SensorValue[Sonar];
			//lightVal = lightVal + SensorValue[Light];
		}
		sonarVal = sonarVal/50;
		//lightVal = lightVal/50;
		//Don't hog CPU
		wait1Msec(25);
	}
}

task joystick()
{
	while (true){
		//Store axis values to variables
		axis1 = vexRT[Ch1];
		axis2 = vexRT[Ch2];
		axis3 = vexRT[Ch3];
		axis4 = vexRT[Ch4];
		//Don't hog CPU
		wait1Msec(25);
	}
}

task shooter()
{
	while(true) {
		//Sonic senor
		if (vexRT[Btn8U == true]){
			//Further than 50 cm
			if (sonarVal > 50) {
				speed = 100;
			}
			//Between 25 cm and 50 cm
			else if (25 < sonarVal && sonarVal  < 50) {
				speed = 50;
			}
			//Less than 25 cm
			else {
				speed = 0;
			}
			//Motor 1 and 2 are already reversed in port configuration
			motor[Shootermotor1] = speed;
			motor[Shootermotor2] = speed;
			motor[Shootermotor3] = speed;
			motor[Shootermotor4] = speed;
			wait1Msec(25);
		}
	}
}

task driving()
{
	while(true){
		//Check the driving code later
		motor[FrontLeft] = axis4 + axis3;
		motor[FrontRight] = axis4 - axis3;
		motor[RearLeft] = axis4 + axis3;
		motor[RearRight] = axis4 - axis3;
		wait1Msec(25);
	}
}

task intake()
{
	while (true){
		//Forwards
		if (vexRT[Btn7U == true]) {
			motor[IntakeMotor] = 80;
		}
		//Backwards
		else if (vexRT[Btn7D == true]) {
			motor[IntakeMotor] = -80;
		}
		//Stop the motor otherwise
		else {
			motor[IntakeMotor] = 0;
		}
		wait1Msec(25);
	}
}

task main()
{
	while (true){
		startTask(sensors);
		startTask(joystick);
		startTask(intake);
		startTask(shooter);
		startTask(driving);
	}
}
