#pragma config(Motor,  port2,           backMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frightMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           fleftMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           intakeMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           middleMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           lshooter1Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lshooter2Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rshooter1Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rshooter2Motor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int turnVar = 1;

	//The 7U button disables the turning
	if (vexRT[Btn7UXmtr2]==1){
		turnVar = turnVar*-1;
	}
	if (turnVar==1){
		//The 2 axis controls the power
		//The 3 axis controls the direction
		float ctrDev = 0;
		while(true) {
			ctrDev = vexRT[Ch3Xmtr2];
			if (ctrDev>0){
				motor[lshooterMotor] = vexRT[Ch2Xmtr2]*(ctrDev/127);
				motor[rshooterMotor] = vexRT[Ch2Xmtr2];
			}
			else if (ctrDev<=0){
				motor[lshooterMotor] = vexRT[Ch2Xmtr2];
				motor[rshooterMotor] = vexRT[Ch2Xmtr2]*(ctrDev/127);
			}
		}
	}
	else if (turnVar==0){
		//Only the 2 axis controls the power
		motor[lshooterMotor] = vexRT[Ch2Xmtr2];
		motor[rshooterMotor] = vexRT[Ch2Xmtr2];
	}
}
