#pragma config(Sensor, dgtl2,  Sonar,          sensorSONAR_cm)
#pragma config(Motor,  port2,           Shootermotor1, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Shootermotor2, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Shootermotor3, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           Shootermotor4, tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
		if (SensorValue[Sonar] > 50) {
			motor[Shootermotor1] = 100;
			motor[Shootermotor2] = 100;
			motor[Shootermotor3] = 100;
			motor[Shootermotor4] = 100;
		}
		else if (25 < SensorValue[Sonar] && SensorValue[Sonar]  < 50) {
			motor[Shootermotor1] = 50;
			motor[Shootermotor2] = 50;
			motor[Shootermotor3] = 50;
			motor[Shootermotor4] = 50;
		}
		else {
			motor[Shootermotor1] = 0;
			motor[Shootermotor2] = 0;
			motor[Shootermotor3] = 0;
			motor[Shootermotor4] = 0;
		}
	}
}
