#pragma config(Motor,  port2,           backMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frightMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           fleftMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           intakeMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           middleMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           lshooter1Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lshooter2Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rshooter1Motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rshooter2Motor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int intake = 0;
int middle = 0;

task main()
{
	while (true){
		//Strafing with the kiwi drive
		motor[frightMotor] = cosDegrees(150)*vexRT[Ch2] + cosDegrees(60)*vexRT[Ch1];
		motor[fleftMotor] = -cosDegrees(150)*vexRT[Ch2] + cosDegrees(60)*vexRT[Ch1];
		motor[backMotor] = -vexRT[Ch1];
		//Rotation
		motor[frightMotor] = vexRT[Ch3];
		motor[fleftMotor] = vexRT[Ch3];
		motor[backMotor] = vexRT[Ch3];
	}
}
