#pragma config(Motor,  port2,           backMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frightMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           fleftMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           intakeMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           middleMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           turntableMotor, tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           rshooterMotor, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           lshooterMotor, tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){
		//Strafing with the kiwi drive
		//motor[frightMotor] = cosDegrees(150)*vexRT[Ch2] + cosDegrees(60)*vexRT[Ch1];
		//motor[fleftMotor] = -cosDegrees(150)*vexRT[Ch2] + cosDegrees(60)*vexRT[Ch1];
		//motor[backMotor] = -vexRT[Ch1];
		//Rotation
		//motor[frightMotor] = vexRT[Ch3];
		//motor[fleftMotor] = vexRT[Ch3];
		//motor[backMotor] = vexRT[Ch3];
		//Front intake motor
		//Upper is towards the back
		if (vexRT[Btn5U]== 1) {

		}else
			//The middle motor
		//Upper is towards the back
		if (vexRT[Btn6U]== 1) {
			motor[middleMotor] = 127;
		}
		else if (vexRT[Btn6D] == 1) {
			motor[middleMotor] = -127;
		}
		else {
			motor[middleMotor] = 0;
		}
		//Turntable motor
		//Upper is towards the back
		if (vexRT[Btn8U]== 1) {
			motor[turntableMotor] = 40;
		}
		else if (vexRT[Btn8D] == 1) {
			motor[turntableMotor] = -40;
		}
		else {
			motor[turntableMotor] = 0;
		}
		//Shooter
		if (vexRT[Btn7U]== 1) {
			motor[rshooterMotor] = 127;
			motor[lshooterMotor] = -127;
		}
		else if (vexRT[Btn7D] == 1) {
			motor[rshooterMotor] = -127;
			motor[lshooterMotor] = 127;
		}
		else {
			motor[rshooterMotor] = 0;
			motor[lshooterMotor] = 0;
		}
	}
}
