#pragma config(Motor,  port2,           backMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frightMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           fleftMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           intakeMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           middleMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           lshooterMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rshooterMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Port 2 is back wheel
// Port 3 is Front Right wheel
// Port 4 is Back Right Wheel
task main() {
	while (1) {
		//Normal drive with rotation
		if (vexRT[Btn6U] == 1) {
			motor[frightMotor] = -vexRT[Ch2];
			motor[fleftMotor] = vexRT[Ch2];
		}
		else if (vexRT[Btn5U] == 1) {
			motor[frightMotor] = vexRT[Ch3];
			motor[fleftMotor] = vexRT[Ch3];
			motor[backMotor] = vexRT[Ch3];
		}
		else if (vexRT[Btn6U] == 0 & vexRT[Btn5U] == 0 )	{
			motor[frightMotor] = 0;
			motor[fleftMotor] = 0;
			motor[backMotor] = 0;
		}
	}
}
