#pragma config(Motor,  port2,           backMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frightMotor,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           fleftMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           intakeMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           middleMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           turntableMotor, tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           rshooterMotor, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           lshooterMotor, tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	//Insert user code here.
	clearTimer(T1);

	while(getTimerValue(T1)<1000){
		motor[frightMotor] = -80;
		motor[fleftMotor] = -80;
	}
	// .....................................................................................

	//AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................
		//Other strafe drive
		if (abs(vexRT[Ch1]) > 25){
			motor[frightMotor] = vexRT[Ch3] - vexRT[Ch4]/2 + vexRT[Ch1]/2;
			motor[fleftMotor] = vexRT[Ch3] + vexRT[Ch4]/2 + vexRT[Ch1]/2;
			motor[backMotor] = -vexRT[Ch4] + vexRT[Ch1]/2;
		}
		else {
			motor[frightMotor] = vexRT[Ch3] - vexRT[Ch4]/2;
			motor[fleftMotor] = vexRT[Ch3] + vexRT[Ch4]/2;
			motor[backMotor] = -vexRT[Ch4];
		}
		//Front intake motor
		//Upper is towards the back
		if (vexRT[Btn5U]== 1 && vexRT[Btn5D] == 0) {
			motor[intakeMotor] = -127;
		}
		else if (vexRT[Btn5U] == 0 && vexRT[Btn5D] == 1) {
			motor[intakeMotor] = 127;
		}
		else {
			motor[intakeMotor] = 0;
		}
		//The middle motor
		//Upper is towards the back
		if (vexRT[Btn6U] == 1 && vexRT[Btn6D] == 0) {
			motor[middleMotor] = -127;
		}
		else if (vexRT[Btn6U] == 0 && vexRT[Btn6D] == 1) {
			motor[middleMotor] = 127;
		}
		else {
			motor[middleMotor] = 0;
		}
		//Turntable motor
		//Upper is towards the back
		if (vexRT[Btn8U] == 1 && vexRT[Btn8D] == 0) {
			motor[turntableMotor] = 20;
		}
		else if (vexRT[Btn8U] == 0 && vexRT[Btn8D] == 1) {
			motor[turntableMotor] = -20;
		}
		else {
			motor[turntableMotor] = 0;
		}
		//Shooter
		if (vexRT[Btn7U]== 1 && vexRT[Btn7D]== 0) {
			motor[rshooterMotor] = -127;
			motor[lshooterMotor] = 127;
		}
		else if (vexRT[Btn7U] == 0 && vexRT[Btn7D]== 1 ) {
			motor[rshooterMotor] = 127;
			motor[lshooterMotor] = -127;
		}
		else {
			motor[rshooterMotor] = 0;
			motor[lshooterMotor] = 0;
		}
		//Break shooter motors
		if (vexRT[Btn7R] == 1){
			motorType[rshooterMotor] = tmotorNone;
			motorType[lshooterMotor] = tmotorNone;
			motorType[rshooterMotor] = tmotorVex393TurboSpeed_MC29;
			motorType[lshooterMotor] = tmotorVex393TurboSpeed_MC29;
		}
		else {}
		//UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
	}
}
