#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (1==1) {
		while (vexRT[Ch1] >0) {
			motor[leftMotor] = vexRT[Ch1];
			motor[rightMotor] = vexRT[Ch1];
		}
		while (vexRT[Ch1] < 0){
			motor[port4] = vexRT[Ch1];
			motor[rightMotor] = vexRT[Ch1];
		}

		motor[leftMotor] = vexRT[Ch3];
		motor[port4] = vexRT[Ch3];

	}
}
